events { worker_connections 1024; }
http {
    map $http_x_piper_secret $is_authorized {
        default "0";
        "" "1";
    }

    server {
        listen 80;
        server_name localhost.yourdomain.com;

        location / {
            if ($is_authorized = "0") {
                return 403;
            }
            proxy_pass http://piper-engine-servers:8099;
            proxy_set_header Host $host;
        }
    }
}
