events { worker_connections 1024; }
http {
    # Check for a specific secret header
    map $http_x_piper_secret $is_authorized {
        default "0";
        "MY_SUPER_SECRET_KEY" "1";
    }

    server {
        listen 80;
        server_name aliceemakpose.yourdomain.com;

        location / {
            # If header is missing or wrong, deny access
            if ($is_authorized = "0") {
                return 403;
            }
            proxy_pass http://piper-engine-servers:8099;
            proxy_set_header Host $host;
        }
    }
}
