key_list = {
        "authorization": str,
        "full_name": str,
        "contact_email": str,
        "form_id": str,
        "value": str,
        "path": str,
        "webhook_tag": str,
        "runtime": str,
        "domain": str,
        "city": str,
        "industry": str,
        "phone": int | str,
        "state": str,
        "description": str,
        "company_name": str,
        "firstname" : str,
        "lastname": str,
        "website": str,
        "lifecyclestage": str,
        "jobtitle": str,
        "email": str,
        "company": str,
        "webhook_url": str,
        "content": str,
        "hs_lead_status": str,
        "contact_id": str,
        "username": str,
        "url": str, 
        "chat_id": str,
        "text": str

    }